#符文标志 不懂不需要改
RuneLogo: '§0§0§0§0§f'
#解锁需要花费的金币
PayMoney: 2000
#符文页无属性时显示
NoAttribute: '&a- &f无'
#默认配置
Normal:
  #符文页名称
  disyname: '&a符文页 &b[ &f{page}&b ]'
  #符文主页标题
  runename: '&a的符文页'
  #默认解锁符文页数
  page: 1
  #默认使用的符文页
  use: 1
RanePage:
  #默认每个玩家能开多少符文页 不能超过27个
  Normal: 5
  authority:
    #拥有VIP1为子节点权限  权限名: "Rune.por.VIP1" 可解锁数量+10
    VIP1: 10
    VIP2: 15
# {Rune_Attributes} 变量的文本
Vau:
  #当变量为0的时候 是否不显示这段
  enable: true
  #Lore
  lore: '&b⊙ &a%Attribute%: &f+%num%'
#符文GUI
Gui:
  #上方物品ID
  ID1: '160:1'
  #下方物品ID
  ID2: '160:1'
  #已解锁物品的材质
  ID3: '340'
  #未解锁的材质
  ID4: '339'
  #已解锁物品显示的Lore
  ID3Lore:
  - '&a&m&l------------------'
  - '&b符文页等级: &f{level}级'
  - '&b符文页属性: '
  - '{Rune_Attribute}'
  - '&a&m&l------------------'
  - ''
  - '&fShirt + 鼠标左键 &6使用此符文页'
  #未解锁物品显示的Lore
  ID4Lore:
  - '&a&m&l------------------'
  - ''
  - '&c该符文页未解锁'
  - '&a可&c左键&a花费 &f{money} &a金币来解锁符文页'
  - ''
  - '&a&m&l------------------'
#提示消息的前缀
Prefix: '&f[&d符文系统&f] &6&l>>> '
#符文制作
RuneItem:
  #代号名
  Test1:
    #符文名
    Name: '&4&l初级力量印记'
    #符文ID
    Id: '353:0'
    #符文等级
    Level: 1
    #符文描述
    Lore:
    - '&7\"花瓣飘落的地方 定是毁灭之地. \"'
    - '&a等级:  &f初级'
    - '&d唯一属性:  &f+0.18 伤害'
    #符文属性
    Attribute:
    - Damage:0.18
  Test2:
    Name: '&4&l初级敏捷印记'
    Id: '351:4'
    Level: 1
    Lore:
    - '&7\"我踏遍的地方 寸草不生 \"'
    - '&a等级:  &f初级'
    - '&d唯一属性:  &f+2% 移速'
    Attribute:
    - Speed:0.02





